### PR TITLE
Add argument to CParser.__init__ for overriding the yacc start symbol.

### PR DESCRIPTION
**Pull request by manueljacob**
This has been very useful for me to be able to parse e.g. expressions directly.

### CODE REVIEW

**Comment by eliben** [comment]
Can you please add a test?

**Comment by manueljacob** [comment]
I didn't really know where to put the test. I hope this is fine.

**Comment by manueljacob** [comment]
I added a bit of documentation to the docstring. Let me know if I should squash the commits.

**Comment by eliben** [comment]
Looks good, thanks. Github lets me squash the commit on merge now :)

**Comment by eliben** [comment]
With this change when pycparser regenerates tables it emits:

```
WARNING: ./pycparser/c_parser.py:511: Rule 'translation_unit_or_empty' defined, but not used
WARNING: There is 1 unused rule
WARNING: Symbol 'external_declaration' is unreachable
WARNING: Symbol 'selection_statement' is unreachable
WARNING: Symbol 'labeled_statement' is unreachable
WARNING: Symbol 'function_definition' is unreachable
WARNING: Symbol 'block_item' is unreachable
WARNING: Symbol 'expression_statement' is unreachable
WARNING: Symbol 'statement' is unreachable
WARNING: Symbol 'iteration_statement' is unreachable
WARNING: Symbol 'compound_statement' is unreachable
WARNING: Symbol 'pp_directive' is unreachable
WARNING: Symbol 'translation_unit_or_empty' is unreachable
WARNING: Symbol 'declaration_list' is unreachable
WARNING: Symbol 'translation_unit' is unreachable
WARNING: Symbol 'init_declarator' is unreachable
WARNING: Symbol 'init_declarator_list' is unreachable
WARNING: Symbol 'declaration' is unreachable
WARNING: Symbol 'pppragma_directive' is unreachable
WARNING: Symbol 'expression_opt' is unreachable
WARNING: Symbol 'block_item_list_opt' is unreachable
WARNING: Symbol 'declaration_list_opt' is unreachable
WARNING: Symbol 'jump_statement' is unreachable
WARNING: Symbol 'init_declarator_list_opt' is unreachable
WARNING: Symbol 'block_item_list' is unreachable
WARNING: Symbol 'decl_body' is unreachable
```

I've reverted the commit for now, until the issue is resolved.

**Pull request merged**
