### PR TITLE
adds visit_FuncDecl method to CGenerator

### PR DESCRIPTION
**Pull request by ssfrr**

### CODE REVIEW

**Comment by eliben** [comment]
Is there a test that can trigger this?

**Comment by ssfrr** [comment]
Just pushed a commit with some testing. I feel like there's a simpler way to exercise this functionality, but I'm not super familiar with the codebase so building a FuncDecl node from scratch is a little over my head, so I'm parsing it from code.

For context, the way I'm using pycparser is to parse header files and generate stubs, so I wanted a way to give a FuncDecl node to a CGenerator instance instead of giving it a full AST. In general being able to generate code for subtrees instead of the full AST seems really useful, I'm not sure if people are using it that way or not.

**Comment by eliben** [comment]
Please squash into a single commit and I'll merge this

**Comment by ssfrr** [comment]
squashed. should be good to go.

**Comment by eliben** [comment]
Thanks for the contribution!

**Pull request merged**
