### PR TITLE
fastfix: func.__doc__ is not mandatory

### PR DESCRIPTION
**Pull request by skob**

### CODE REVIEW

**Comment by eliben** [comment]
What is this fixing?

**Comment by skob** [comment]
func.__doc__ can be empty and in this case I see this error:
```
  File "/srv/projects/venv/local/lib/python2.7/site-packages/pycparser/plyparser.py", line 112, in _create_param_rules
    param_rule.__doc__ = func.__doc__.replace('xxx', xxx).replace('yyy', yyy)
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by eliben** [comment]
Yes, I get that. *When* can it be empty, though?

**Comment by skob** [comment]
i've got this bug while running digitalocean/netbox via uwsgi:
```
Traceback (most recent call last):
  File "/srv/projects/netbox/netbox/netbox/wsgi.py", line 8, in <module>
    application = get_wsgi_application()
  File "/srv/projects/venv/local/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/srv/projects/venv/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/projects/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/srv/projects/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./secrets/models.py", line 5, in <module>
    from Crypto.Cipher import AES, PKCS1_OAEP
  File "/srv/projects/venv/local/lib/python2.7/site-packages/Crypto/Cipher/__init__.py", line 3, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/srv/projects/venv/local/lib/python2.7/site-packages/Crypto/Cipher/_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/srv/projects/venv/local/lib/python2.7/site-packages/Crypto/Util/_raw_api.py", line 61, in <module>
    ffi = FFI()
  File "/srv/projects/venv/local/lib/python2.7/site-packages/cffi/api.py", line 63, in __init__
    from . import cparser
  File "/srv/projects/venv/local/lib/python2.7/site-packages/cffi/cparser.py", line 7, in <module>
    import pycparser
  File "/srv/projects/venv/local/lib/python2.7/site-packages/pycparser/__init__.py", line 14, in <module>
    from .c_parser import CParser
  File "/srv/projects/venv/local/lib/python2.7/site-packages/pycparser/c_parser.py", line 20, in <module>
    class CParser(PLYParser):
  File "/srv/projects/venv/local/lib/python2.7/site-packages/pycparser/plyparser.py", line 95, in template
    _create_param_rules(cls, method)
  File "/srv/projects/venv/local/lib/python2.7/site-packages/pycparser/plyparser.py", line 112, in _create_param_rules
    param_rule.__doc__ = func.__doc__.replace('xxx', xxx).replace('yyy', yyy)
```

**Comment by eliben** [comment]
This seems to stem from a mis-usage of pycparser. See https://github.com/eliben/pycparser/pull/198 for a long discussion

**Comment by eliben** [comment]
Also note this already exists to some extent: https://github.com/eliben/pycparser/blob/master/pycparser/plyparser.py#L105

**Comment by skob** [comment]
hmmmm
i don't see this line in pip version. It's ok? :-)

```
pip search pycparser
pycparser (2.18)             - C parser in Python
  INSTALLED: 2.18 (latest)```

```
def template(cls):
    """ Class decorator to generate rules from parameterized rule templates.

    See `parameterized` for more information on parameterized rules.
    """
    for attr_name in dir(cls):
        if attr_name.startswith('p_'):
            method = getattr(cls, attr_name)
            if hasattr(method, '_params'):
                delattr(cls, attr_name)  # Remove template method
                _create_param_rules(cls, method)
    return cls
```

**Comment by eliben** [comment]
It went in https://github.com/eliben/pycparser/commit/673accec311a027c22b0718d753f8da922915305 which was after the 2.18 release

**Comment by skob** [comment]
ok , thanks!
i'll be wait new version in pip

**Pull request closed without merging**
