### PR TITLE
Add support for continuing parsing & different start symbol

### PR DESCRIPTION
**Pull request by eqvinox**
Updated version of #120, with tests & demo. Also provides a superset of the (reverted) #159.

All feedback from both #120 and #159 should be addressed.

### CODE REVIEW

**Comment by eliben** [comment]
Sorry, but I'm still not too excited about this kind of change. I feel it addresses a very specific use-case of pycparser which isn't very generally useful, but it adds considerable complexity in the trickiest part of the project - interaction with PLY and its Yacc table generation; this backfired many times in the past due to the huge stack of projects implicitly dependent on pycparser (because of cffi), and I simply don't have the bandwidth to deal with these issues again.

**Comment by eqvinox** [comment]
This is why my original implementation in #119 used a special token to switch the parser state. It looks odd, but is actually far cleaner than messing with PLY. I can switch back to that.

I believe the usefulness is sufficiently evident from 2 people independently needing the feature, cooking up patches, and submitting PRs.

**Comment by eliben** [comment]
I feel a bit bad about rejecting PRs and it's great to see the work folks are willing to put into pycparser, but if there's any chance for me to continue maintaining this project with my dwindling free time, I have to aggressively restrict its scope.

On Github it's easy to keep enhancements to a project in a fork. https://github.com/inducer/pycparserext would be the prime example for this

**Comment by eqvinox** [comment]
... or maybe you could ask someone for help in maintaining, like maybe the cffi people.

**Pull request closed without merging**
