### PR TITLE
Add support for Python 3.10

### PR DESCRIPTION
**Pull request by hugovk**
Due out in a couple of weeks, on 2021-10-04:

https://www.python.org/dev/peps/pep-0619/

### CODE REVIEW

**Comment by hugovk** [comment]
By the way, there's an estimated $251.43/month available for the maintainers of pycparser:

* https://tidelift.com/lifter/search/pypi/pycparser

**Comment by eliben** [comment]
I'm OK with waiting for 3.10 to be properly released, at which point presumably we don't need the `-dev` postfix?

**Comment by hugovk** [comment]
Yep, after the full release we can drop the `-dev`.

Fine by me to wait, although the benefit of testing now on `3.10-dev` is it prevents merging incompatible PRs now. Helps avoid surprises later.

(For packages that provide compiled binary wheels, such as NumPy, Pandas and Pillow, there's a strong argument for releasing for 3.10 before the official release date, because it helps dependant packages test much more easily. And they have. But for pure Python packages, it's not so important.)

**Comment by eliben** [comment]
Seems like Python 3.10 was released. If Github Actions supports 3.10 in its workflows, please update the PR and ping it - I will merge

**Comment by hugovk** [comment]
GHA now supports 3.10 final, updated - ping @eliben!

**Pull request merged**
